<?php
/**
 * Created by PhpStorm.
 * User: 老王专用
 * Date: 2019/6/1
 * Time: 15:59
 */

namespace app\admin\controller;


use think\Cache;
use think\Controller;

class BaseController extends Controller
{
    protected function _initialize()
    {
        $key = getRandChar(15);
        if (!Cache::has('key')){
            $key = Cache::get('key');
            $admin = json_decode($key,true);
            return $this->redirect(url('index/login'));
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}